/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        DishStack stack = new DishStack(5);

        Dish oneDish = new Dish("A dish with one fish pattern on it");
        Dish twoDish = new Dish("A dish with two fish patterns on it");
        Dish redDish = new Dish("A dish with a red fish pattern on it");
        Dish blueDish = new Dish("A dish with a blue fish pattern on it");

        int stackSize = stack.size();

        stack.push(oneDish);
        stack.push(twoDish);
        stack.push(redDish);
        stack.push(blueDish);

        int sizeAfterPushes = stack.size();

        System.out.println("Initial stack size: " + stackSize);
        System.out.println("Stack size after pushes: " + sizeAfterPushes);

        Dish peekedDish = stack.peek();
        
        System.out.println(peekedDish.description);

        Dish poppedDish = stack.pop();

        System.out.println(poppedDish.description);

        Dish anotherPoppedDish = stack.pop();

        System.out.println(anotherPoppedDish.description);

        int finalStackSize = stack.size();
        System.out.println("Final stack size: " + finalStackSize);

        stack.push(blueDish);
        stack.push(blueDish);
        stack.push(blueDish);
        stack.push(blueDish); // will display error message
        stack.push(blueDish); // will display error message


    }
}
